# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e4d04ea91af4d395b46aac260c6064ed5ef3de425fe50111c09234607cd49b03deb2a3abe1d7edcee5c1a782dd1d7db13a890237289480ef66970d7e320cfe

test:
  secret_key_base: 6621b863f33a55e16f15b140ab80b6a12501d9944fc8d6ea002118a9a88fd68abdc4af9078c74513f2bb48418da7bae3a76c37ff4dbfe46ca0628176d066133c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
